import type { Metadata } from "next";

import Navbar from "@/components/common/Navbar";

export const metadata: Metadata = {
  title: "Biblioteca Star Wars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
