import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"

import "../globals.css";

import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Biblioteca Star Wars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <main className="mt-24">
          {children}
        </main>
        <Toaster />
      </div>
    </>
  );
}
